// <auto-generated />
namespace Kundbolaget.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initCreate_sprint4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initCreate_sprint4));
        
        string IMigrationMetadata.Id
        {
            get { return "201701052238597_initCreate_sprint4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
